### ISSUE TITLE
 Could not lex the character code 194

### ISSUE THREAD

**Issue by Jaswanth-Devarinti** [JohnGiorgi/DeCLUTR#231]
I am getting this error while training on custom data.
```
2021-09-07 05:49:44,531 - INFO - transformers.file_utils - TensorFlow version 2.6.0 available.
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.7/dist-packages/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/allennlp/commands/train.py", line 118, in train_model_from_args
    file_friendly_logging=args.file_friendly_logging,
  File "/usr/local/lib/python3.7/dist-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/usr/local/lib/python3.7/dist-packages/allennlp/common/params.py", line 491, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
RuntimeError: STATIC ERROR: /content/drive/MyDrive/Tatasky data/Declutter_sent_embed/declutr.jsonnet:81:44: Could not lex the character code 194
```
Its because of allennlp, is there anything I can do.
Thank you

**Comment by JohnGiorgi** [comment]
Hmm, it seems like there is a character in your jsonnet config at `/content/drive/MyDrive/Tatasky data/Declutter_sent_embed/declutr.jsonnet` that is causing trouble. The error says it is on line 81 column 44 I believe. Maybe check that line?

**Comment by Jaswanth-Devarinti** [comment]
Will do, thank you for the response.
